spring.application.name=gestion-dons
spring.datasource.url=jdbc:mysql://localhost:3306/dons_solidaire
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
